### ISSUE TITLE
(Forge) Crash on worldgen

### ISSUE THREAD

**Issue by InsaanNotFound** [SpudsMods/NewWorld#1]
```
[23:09:21] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ee7740f1-e553-42f2-b378-0f313258d7e4
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 8/24/22, 11:09 PM
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:meadow]=net.minecraft.world.level.biome.Biome@3abdc00e}, Reference{ResourceKey[minecraft:worldgen/biome / newworld:wooded_meadow]=net.minecraft.world.level.biome.Biome@6bf473e0}]
	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at net.minecraft.world.level.biome.BiomeSource.m_204231_(BiomeSource.java:70) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:terrablender.mixins.json:MixinBiomeSource,pl:mixin:A}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2318!/:?] ...
```

**Comment by ebo2022** [comment]
can you send the full latest.log?

**Comment by InsaanNotFound** [comment]
I checked latest.log which I will send with this message
[latest.log](https://github.com/SpudsMods/NewWorld/files/9422672/latest.log)
Although I seem to have been misleaded, the issue is in fact incompability of William Wyther's Overhauled Overworld in its mod form (https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld/files/3947035). Precisely a feature biome order cycle that crashes the game. Biomes involved are **minecraft:worldgen/biome / newworld:wooded_meadow** and **minecraft:worldgen/biome / wythers:flowering_pantanal**
```
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / newworld:wooded_meadow]=net.minecraft.world.level.biome.Biome@63410c4d}, Reference{ResourceKey[minecraft:worldgen/biome / wythers:flowering_pantanal]=net.minecraft.world.level.biome.Biome@650f6991}]
	at net.minecraft.world.level.biome.BiomeSource.m_186727_(BiomeSource.java:136) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.world.level.biome.BiomeSource.m_204231_(BiomeSource.java:70) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%2318!/:?]
	at net.minecraft.world.level.biome.BiomeSource.m_186733_(BiomeSource.java:258) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2323!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23313!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[25Aug2022 09:53:27.078] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
```
So yeah, this is a mod incompability. This is as follows Wyther's JSON regarding this precise biome (had to change format to txt for Github to accept it):
[flowering_pantanal.txt](https://github.com/SpudsMods/NewWorld/files/9422727/flowering_pantanal.txt)

**Comment by ebo2022** [comment]
We probably won't directly fix this but we will make sure people know this is an incompatibility
